# Generated by Django 2.2.1 on 2019-05-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasta',
            new_name='NotPizza',
        ),
    ]
