# Generated by Django 2.2.1 on 2019-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190522_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notpizza',
            name='price',
        ),
        migrations.AddField(
            model_name='notpizza',
            name='extracheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notpizza',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notpizza',
            name='largeprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='notpizza',
            name='regprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='notpizza',
            name='topping',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotPizzaToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('sub', models.ManyToManyField(blank=True, related_name='toppings', to='orders.NotPizza')),
            ],
        ),
    ]
