# Generated by Django 2.2.1 on 2019-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190522_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='notpizza',
            name='type',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
