# Generated by Django 2.2.1 on 2019-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_notpizza_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpizza',
            name='largeprice',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
