# Generated by Django 2.2.1 on 2019-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190522_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpizza',
            name='largeprice',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
