# Generated by Django 2.2.1 on 2019-05-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190522_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notpizza',
            name='topping',
        ),
    ]
