# Generated by Django 2.2.1 on 2019-05-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190522_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notpizza',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Category'),
        ),
    ]
