# Generated by Django 2.2.1 on 2019-05-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_notpizza_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpizza',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='orders.Category'),
        ),
    ]
