# Generated by Django 2.2.1 on 2019-05-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190522_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('regprice', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('large', models.BooleanField(default=False)),
                ('largeprice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pizza', to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sub', models.ManyToManyField(blank=True, related_name='piztop', to='orders.Pizza')),
            ],
        ),
    ]
