# Generated by Django 2.2.1 on 2019-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
