# Generated by Django 2.2.1 on 2019-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cartitems_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=5, null=True)),
                ('item', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
