# Generated by Django 2.2.1 on 2019-05-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_vieworders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieworders',
            name='price',
        ),
    ]
