# Generated by Django 2.2.1 on 2019-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_vieworders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topamount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
