# Generated by Django 2.2.1 on 2019-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_pizza_topamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='topping',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
